### ISSUE TITLE
Can we Add Deepface library to this.

### ISSUE THREAD

**Issue by Raghucharan16** [KaSaNaa/RetroSpectra#2]
Deepface wraps up the different state of art algorithms and have out performing accuracies when compared to other models.
It facilitates Face Detection, Face Recognition and Facial Attribute analysis. and the cool thing is it much lighter framework such that all activities can be done in a single file.

**Comment by KaSaNaa** [comment]
Yes, you can add the DeepFace library to this project, but you might need to refactor your code to fully leverage its capabilities.
